### ISSUE TITLE
Library does not build on ESP8266 platform

### ISSUE THREAD

**Issue by techparva** [mongoose-os-libs/pppos#7]
Using mos latest as well as release gives following error-

/home/aashish/mongoose-os-apps/rf_gsm_gateway/deps/pppos/src/mgos_pppos.c:28:27: fatal error: netif/ppp/ppp.h: No such file or directory
 #include "netif/ppp/ppp.h"
                           ^
compilation terminated.

**Comment by gebv** [comment]
l have the same error for esp8266 and esp32 platforms

mos.yml
```
author: mongoose-os
description: A JS-enabled demo Mongoose OS firmware
# arch: PLATFORM
version: 1.0
manifest_version: 2017-05-18
libs_version: ${mos.version}
modules_version: ${mos.version}
mongoose_os_version: ${mos.version}

config_schema:
  - ["mqtt.server", "iot.eclipse.org:1883"]
  - ["i2c.enable", true]
  - ["pppos.enable", true]
  - ["pppos.uart_no",1]
  - ["pppos.baud_rate", 115200]
  - ["pppos.connect_cmd", "ATD*99***1#"]
  - ["pppos.apn", "internet"]
  - ["pppos.user", "gdata"]
  - ["pppos.pass", "gdata"]
  - ["pppos.hexdump_enable", true]
  - ["wifi.sta.enable", false]

tags:
  - js

filesystem:
  - fs

libs:
  - origin: https://github.com/mongoose-os-libs/boards
  - origin: https://github.com/mongoose-os-libs/js-demo-bundle
  - origin: https://github.com/mongoose-os-libs/pppos

```

mos Version: 2.16.0

```
mos build  --platform esp8266 --verbose
...
CC    /data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/mjs/src/mos_mjs.c
  CC    /data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/modules/mjs/mjs.c
  CC    /data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/mjs/esp8266/src/esp8266_mjs.c
  CC    /data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/js-demo-bundle/src/mgos_js_demo_bundle.c
  CC    /data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/pppos/src/mgos_pppos.c
  CC    /data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/build/gen/ffi_exports.c
  CC    /mongoose-os/src/common/cs_file.c
  CC    /mongoose-os/src/common/cs_rbuf.c
  CC    /mongoose-os/src/mgos_config_util.c
/data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/pppos/src/mgos_pppos.c:27:27: fatal error: netif/ppp/ppp.h: No such file or directory
 #include "netif/ppp/ppp.h"
                           ^
compilation terminated.
/data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/deps/modules/mongoose-os/platforms/esp8266/Makefile.build:398: recipe for target '/data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/build/objs/mgos_pppos.c.o' failed
make: *** [/data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_668243625/build/objs/mgos_pppos.c.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/app'
Error: exit status 2
```

```
mos build  --platform esp32 --verbose
...
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_a2dp_api.o
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_gattc_api.o
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_blufi_api.o
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_gap_ble_api.o
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_gatts_api.o
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_gatt_common_api.o
CC /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/bluedroid/api/esp_hf_client_api.o
AR /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt/libbt.a
make[1]: Leaving directory '/data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/bt'
Generating libbt.a.sections_info
Generating esp32.project.ld
LD /data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/build/objs/app1.elf
esptool.py v2.8-dev
    App size: 1599296 of 1572864 (101%)
App is too big
/data/fwbuild-volumes/2.16.0/apps/app1/esp32/build_contexts/build_ctx_257041715/deps/modules/mongoose-os/platforms/esp32/Makefile.build:210: recipe for target 'app-bin-check' failed
make: *** [app-bin-check] Error 1
make: Leaving directory '/app'
Error: exit status 2
/go/src/github.com/mongoose-os/mos/mos/build_local.go:693:
/go/src/github.com/mongoose-os/mos/mos/build_local.go:680:
/go/src/github.com/mongoose-os/mos/mos/build_local.go:445:
/go/src/github.com/mongoose-os/mos/mos/build.go:220:
/go/src/github.com/mongoose-os/mos/mos/build.go:163:
/go/src/github.com/mongoose-os/mos/mos/main.go:196: build failed
Error: /private/tmp/mos-20191107-31823-1o4s33s/mos-adcad3f2ca90789fc5426dc8c6302383effaa415/src/cesanta.com/go/src/github.com/mongoose-os/mos/mos/build_remote.go:326: build failed
/private/tmp/mos-20191107-31823-1o4s33s/mos-adcad3f2ca90789fc5426dc8c6302383effaa415/src/cesanta.com/go/src/github.com/mongoose-os/mos/mos/build.go:220:
```

please advice
